version: '3.8'

x-common-variables: &common-variables
  REACT_APP_DOMAIN: http://130.61.53.115

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:3050"
      - "3000:3050"

  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      <<: *common-variables

  client:
    stdin_open: true
    environment:
      <<: *common-variables
    build:
      dockerfile: Dockerfile
      context: ./
